### PR TITLE
Fix use of deprecated API in package.js

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Fixes use of deprecated API in `package.js` which has been finally removed in Meteor 2.3

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@Grubba27 can you please merge this and release a new version. This is way overdue.

**Comment by Grubba27** [comment]
This could be a 1.5.2? not sure what do you thing?

**Comment by StorytellerCZ** [comment]
Yes, it is a fix, so according to semantic versioning it should be a patch release.

**Comment by Grubba27** [comment]
done! 1.5.2

**Pull request merged**
