### PR TITLE
feature : async job

### PR DESCRIPTION
**Pull request by parhelium**
Added async execution of job, which gives 2 benefits : 
- `finishedAt` field has accurate date,
- log ''SyncedCron: Finished ... " is shown in the right moment, after a job is finished 

By default it is disabled : ` isAsync : false `

### CODE REVIEW

**Comment by tmeasday** [comment]
Hey @parhelium - have you considered just job properly syncronous?

Something like
```
    SyncedCron.add({
      ...
      job: Meteor.wrapAsync(job)
     });
```

**Comment by parhelium** [comment]
For simple use cases you are absolutely right.

Meteor.wrapAsync assumes that callback function has 2 arguments : **err**, **result**
In my case callback takes 3 arguments : **err**, **stdout**, **meta**

```
curl.request({ url: 'http://google.com', pretend: true }, function (err, stdout, meta) {
    console.log('%s %s', meta.cmd, meta.args.join(' '));
});
```
[curlRequest](https://github.com/chriso/curlrequest) 

I don't know how to solve this issue using Meteor.wrapAsync, so I decided to create this pullRequest.

Please let me know if you see other solution for it.

**Comment by tmeasday** [comment]
@parhelium you can just wrap it in an function with that API:

```
Meteor.wrapAsync(function(args, cb) {
   curl.request(args, function(err, stdout,meta) {
     cb(err, {stdout: stdout, meta:meta});
   });
});
```

Does that work?

**Comment by parhelium** [comment]
@tmeasday Thank you, your suggestion definitely solves my issue. It means there is no need for this pull request.

**Comment by parhelium** [comment]
I have now realized one issue ( in my case) when I'm using Meteor.wrapAsync - it is blocking.

That means my schedules won't run until the last one will finish.
For example if I want to run job every 10 seconds and job last at least 20 seconds, then in the end my schedule will run every 20 seconds.

How can I solve this issue ?

**Comment by tmeasday** [comment]
I guess this package doesn't support parallel/simultaneous job execution right now (is that what you'd expect @zol?). 

You can do the opposite of what we discussed above by wrapping your code in `Meteor.defer()`. But I guess you are hoping for parallel execution (i.e. the second job starts before the first considers itself finished). I'm not sure what the implications of that are but I have a feeling people could find it quite surprising in some cases.

**Comment by zol** [comment]
@tmeasday @parhelium - I'm not sure the question here is. Synced-cron internally uses `Meteor.setTimeout` to run jobs so they will run asynchronously out of the box. Beyond ensuring that a job named X scheduled to run at Y time will only be run once across your cluster, synced-cron does nothing more to try to align job scheduling based on job duration.

**Comment by tmeasday** [comment]
@zol so the second iteration of job X can run while the first iteration is still continuing? That's cool then.

**Comment by zol** [comment]
Yes, there's nothing in synced-cron that would terminate the first iteration, or block the second from starting.

**Comment by parhelium** [comment]
I think this is not the problem of SyncedCron or Meteor.wrapAsync, but only the way how job is written.

```
var job = function( intendedAt , cb ){
    Meteor.setTimeout( function () {
      // blocks SyncedCron from executing next job if cb wasn't called yet
      // if job is supposed to run every 2 seconds, then it will run every 10 seconds
      // cb && cb()
    }, 10000 )

    // non blocking solution
    // cb && cb();
  }
```

I was trying to use SyncedCron logs and always have them in right order ( started, job logs, finished ).
It looks like it is not possible to do that without using the "blocking way".

Thank you for SyncedCron and quick replies.

**Pull request closed without merging**
